Reduced usage of Internal code
composewell/streamly-examples pull request #13
Opened 2021-01-25 11:39 UTC by pranaysashank

2021-01-25 12:09 UTC, harendra-kumar requested changes
Can we use full names of the modules in imports e.g. Stream instead of S, Fold instead of FL etc.

2021-01-25 12:09 UTC, harendra-kumar commented on examples/Examples.hs
> +import qualified Streamly.Internal.Unicode.Stream as U (words, unwords)
We can replace these with their definitions and plan to expose `Stream.interpose` in 0.8.0.

2021-01-25 12:09 UTC, harendra-kumar commented on examples/Examples.hs
> +       (fromList, fold, enumerateFromToIntegral, identity, outerProduct, map)
We can expose these in 0.8.0.

2021-01-25 12:09 UTC, harendra-kumar commented on examples/Examples.hs
> +import qualified Streamly.Internal.Network.Socket as SK (writeStrings)
We can expand this to its definition and expose everything required for that definition.

2021-01-25 12:09 UTC, harendra-kumar commented on examples/Examples.hs
> +       (intercalateSuffix)
We can expose this in 0.8.0.

2021-01-25 12:09 UTC, harendra-kumar commented on examples/FromFileClient.hs
> +import qualified Streamly.Internal.Network.Inet.TCP as TCP (writeChunks)
We can expose this in 0.8.0.

2021-01-25 12:09 UTC, harendra-kumar commented on examples/HandleIO.hs
> +import qualified Streamly.Internal.Unicode.Stream as US (lines)
`lines` can be expanded to its definition.

2021-01-25 12:09 UTC, harendra-kumar commented on examples/Rate.hs
> +import qualified Streamly.Internal.Data.Stream.IsStream as S (timestamped)
We can expose this in 0.8.0.

2021-01-27 04:47 UTC, pranaysashank commented on examples/WordClassifier.hs
> +import qualified Streamly.Internal.Data.Unfold as UF (fold)
We can't use Stream.fold without using more internal functions

2021-01-27 04:52 UTC, pranaysashank commented on examples/WordClassifier.hs
> +import qualified Streamly.Internal.Unicode.Stream as S (words)
We need isSpace to inline for good performance, perhaps we can copy its definition in the example files.

2021-01-27 07:01 UTC, harendra-kumar requested changes
We can move `isAlpha`, and `toLower` to `Streamly.Internal.Unicode.Char` module. Also, `isSpace`.

We can keep the usage of `words` if `isSpace` does not inline. Perf needs to remain good.

Raise an issue for proposed streamly changes.

2021-04-14 11:20 UTC, merged