Add FileSystem Events Example
composewell/streamly-examples pull request #4
Opened 2020-11-09 05:52 UTC by rnjtranjan

2020-11-13 14:09 UTC, harendra-kumar requested changes

2020-11-13 14:09 UTC, harendra-kumar commented on examples/FileSystemEvent.hs
> +    watchPaths (NonEmpty.fromList paths)
We can directly use `watchTrees` here instead of creating the `watchPaths` function.

2020-12-22 14:40 UTC, rnjtranjan commented
Fixes #6

2020-12-23 06:02 UTC, harendra-kumar commented
GHC-8.8 build is failing with a compilation error.

2020-12-31 07:15 UTC, harendra-kumar commented
We can remove the x86 build from CI.

2020-12-31 07:42 UTC, harendra-kumar commented
Need to fix ghcjs build. Even though the network package compiles with ghcjs we cannot really use it, need to disable some examples for ghcjs as before.

2021-01-21 14:20 UTC, merged